import React from 'react'
import { BlogCard } from '../components/BlogCard'
import NavBar from '../components/NavBar'

const Blogs = () => {
  return (
    <div>
      <div><NavBar/></div>
      <div className='flex justify-center'>
          <div className='flex flex-col jsutify-center max-w-2xl'>
              <BlogCard authorName="Aditya Sharma" title="The Silent Revolution of AI in Everyday Life" content="Artificial Intelligence is no longer a futuristic concept reserved for science fiction. It has quietly integrated itself into our daily routines, transforming the way we communicate, work, shop, and even make decisions. From personalized recommendations on streaming platforms to intelligent navigation systems that optimize our routes, AI has become an invisible assistant that powers modern life.\n\nOne of the most significant impacts of AI can be seen in productivity. Businesses are leveraging machine learning algorithms to automate repetitive tasks, allowing employees to focus on more strategic and creative work. Customer support systems powered by AI can now resolve common issues instantly, improving user satisfaction while reducing operational costs.\n\nHealthcare is another field experiencing rapid transformation. AI-driven diagnostic tools can analyze medical images with remarkable accuracy, helping doctors detect diseases earlier than ever before. Researchers are also using AI to accelerate drug discovery, reducing the time required to bring life-saving treatments to market.\n\nDespite its benefits, the widespread adoption of AI raises important questions about privacy, ethics, and employment. As organizations collect more data to train intelligent systems, ensuring transparency and protecting user information become critical responsibilities. Governments and technology leaders must work together to establish guidelines that encourage innovation while safeguarding society.\n\nLooking ahead, AI will continue to evolve and influence nearly every industry. The challenge is not whether AI will shape our future, but how we choose to guide its development. By embracing responsible innovation, we can harness the power of artificial intelligence to create a more efficient, accessible, and prosperous world." publishedDate="2026-06-19" />
              <BlogCard authorName="Aditya Sharma" title="The Silent Revolution of AI in Everyday Life" content="Artificial Intelligence is no longer a futuristic concept reserved for science fiction. It has quietly integrated itself into our daily routines, transforming the way we communicate, work, shop, and even make decisions. From personalized recommendations on streaming platforms to intelligent navigation systems that optimize our routes, AI has become an invisible assistant that powers modern life.\n\nOne of the most significant impacts of AI can be seen in productivity. Businesses are leveraging machine learning algorithms to automate repetitive tasks, allowing employees to focus on more strategic and creative work. Customer support systems powered by AI can now resolve common issues instantly, improving user satisfaction while reducing operational costs.\n\nHealthcare is another field experiencing rapid transformation. AI-driven diagnostic tools can analyze medical images with remarkable accuracy, helping doctors detect diseases earlier than ever before. Researchers are also using AI to accelerate drug discovery, reducing the time required to bring life-saving treatments to market.\n\nDespite its benefits, the widespread adoption of AI raises important questions about privacy, ethics, and employment. As organizations collect more data to train intelligent systems, ensuring transparency and protecting user information become critical responsibilities. Governments and technology leaders must work together to establish guidelines that encourage innovation while safeguarding society.\n\nLooking ahead, AI will continue to evolve and influence nearly every industry. The challenge is not whether AI will shape our future, but how we choose to guide its development. By embracing responsible innovation, we can harness the power of artificial intelligence to create a more efficient, accessible, and prosperous world." publishedDate="2026-06-19" />
              <BlogCard authorName="Aditya Sharma" title="The Silent Revolution of AI in Everyday Life" content="Artificial Intelligence is no longer a futuristic concept reserved for science fiction. It has quietly integrated itself into our daily routines, transforming the way we communicate, work, shop, and even make decisions. From personalized recommendations on streaming platforms to intelligent navigation systems that optimize our routes, AI has become an invisible assistant that powers modern life.\n\nOne of the most significant impacts of AI can be seen in productivity. Businesses are leveraging machine learning algorithms to automate repetitive tasks, allowing employees to focus on more strategic and creative work. Customer support systems powered by AI can now resolve common issues instantly, improving user satisfaction while reducing operational costs.\n\nHealthcare is another field experiencing rapid transformation. AI-driven diagnostic tools can analyze medical images with remarkable accuracy, helping doctors detect diseases earlier than ever before. Researchers are also using AI to accelerate drug discovery, reducing the time required to bring life-saving treatments to market.\n\nDespite its benefits, the widespread adoption of AI raises important questions about privacy, ethics, and employment. As organizations collect more data to train intelligent systems, ensuring transparency and protecting user information become critical responsibilities. Governments and technology leaders must work together to establish guidelines that encourage innovation while safeguarding society.\n\nLooking ahead, AI will continue to evolve and influence nearly every industry. The challenge is not whether AI will shape our future, but how we choose to guide its development. By embracing responsible innovation, we can harness the power of artificial intelligence to create a more efficient, accessible, and prosperous world." publishedDate="2026-06-19" />
          </div>
      </div>
    </div>
  )
}


export default Blogs